name: calendar_agent
mode: builtin
activated_tools:
  # Outlook Calendar Tools
  - list_outlook_events
  - create_outlook_event
  - update_outlook_event
  - delete_outlook_event
  - find_free_time_outlook
  # Teams Meeting Tools
  - create_teams_meeting
  - list_teams_meetings
  - update_teams_meeting
  - cancel_teams_meeting
  - get_teams_meeting_details
  - schedule_recurring_teams_meeting
config:
  # Outlook Calendar Configuration
  outlook_calendar:
    client_id: "${oc.env:OUTLOOK_CLIENT_ID}"
    client_secret: "${oc.env:OUTLOOK_CLIENT_SECRET}"
    tenant_id: "${oc.env:OUTLOOK_TENANT_ID}"
    # access_token: "${oc.env:OUTLOOK_ACCESS_TOKEN}"  # Alternative to client credentials

  # Teams Calendar Configuration
  teams_calendar:
    client_id: "${oc.env:TEAMS_CLIENT_ID}"
    client_secret: "${oc.env:TEAMS_CLIENT_SECRET}"
    tenant_id: "${oc.env:TEAMS_TENANT_ID}"
    # access_token: "${oc.env:TEAMS_ACCESS_TOKEN}"  # Alternative to client credentials

  # Optional LLM configuration for enhanced calendar management
  config_llm:
    model_provider:
      type: "${oc.env:UTU_LLM_TYPE}"
      model: "${oc.env:UTU_LLM_MODEL}"
      api_key: "${oc.env:UTU_LLM_API_KEY}"
      base_url: "${oc.env:UTU_LLM_BASE_URL}"
    model_params:
      temperature: 0.7
      max_tokens: 1000
