name: supabase
mode: mcp
activated_tools:
  - list_tables
  - execute_sql
config:
  command: npx
  args: ["-y", "@supabase/mcp-server-supabase@latest", "--access-token", "${oc.env:SUPABASE_ACCESS_TOKEN}"]
  env:
    SUPABASE_ACCESS_TOKEN: ${oc.env:SUPABASE_ACCESS_TOKEN}
    SUPABASE_PROJECT_REF: ${oc.env:SUPABASE_PROJECT_REF}
