name: supabase
mode: mcp
activated_tools:
  - list_tables
  - execute_sql
config:
  command: npx
  args: ["-y", "@supabase/mcp-server-supabase@latest", "--access-token", "${oc.env:SUPABASE_ACCESS_TOKEN}", "--project-ref", "kclhwddhqtlmcjfpebz"]
  env:
    SUPABASE_ACCESS_TOKEN: ${oc.env:SUPABASE_ACCESS_TOKEN}
