name: user_profile
mode: builtin
activated_tools: null
config:
  USER_PROFILE_API_URL: ${oc.env:USER_PROFILE_API_URL,http://localhost:3000/api/user-profile}
  SUPABASE_SERVICE_ROLE_KEY: ${oc.env:SUPABASE_SERVICE_ROLE_KEY}
  REQUEST_TIMEOUT: 30
config_llm:
  model_provider:
    type: ${oc.env:UTU_LLM_TYPE}
    model: ${oc.env:UTU_LLM_MODEL}
    api_key: ${oc.env:UTU_LLM_API_KEY}
    base_url: ${oc.env:UTU_LLM_BASE_URL}
  model_params:
    temperature: 0.7
    top_p: 0.9
    parallel_tool_calls: false
